# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc4efce1d220e8d4f9907e2f877a1f9459cd84f6d689beafd50806a22f2d35585210e3d2716045a4c4b5d045400a396879cda2d0e17037a6bdc26bcad6ea1278

test:
  secret_key_base: 99e6754c7caf0ad47fef571c893872782818fe24792fa8d66f5b0c1bc158a8ce0edc904959ddac4218a6c6c855094f34e00ebd4e3b473de4b7d2fd56785f3e68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
